// v14 drops the course bundles: lesson content now lives server-side and is fetched
// per lesson from /api/course, which enforces entitlement. Precaching the old public
// bundles would have kept serving the entire paid course from cache to anyone who
// had visited before the change — the version bump is what actually evicts them.
//
// v13 narrowed the app to three surfaces: the intro page, the course, and the ideas
// desk. Due Diligence, FX Intelligence and the standalone manifesto are retired —
// their routes redirect home (see vercel.json) and precaching them would keep
// serving dead pages to anyone who had already visited. The version bump is what
// evicts them from existing installs.
const CACHE_NAME = 'scere-markets-v14';
const ASSETS_TO_CACHE = [
  './',
  './index.html',
  './nav.js',
  './research.html',
  './research.js',
  './learn.html',
  './lesson.html',
  './learn.js',
  './country-indicator-copy.js',
  './crypto-labs.js',
  './instruments.js',
  './fund-facts.js',
  './styles.css',
  './manifest.json',
  'https://cdn.tailwindcss.com'
];

// 1. Install: cache the app shell.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS_TO_CACHE))
  );
  self.skipWaiting();
});

// 2. Activate: drop old cache versions.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.map((key) => (key !== CACHE_NAME ? caches.delete(key) : undefined)))
    )
  );
  self.clients.claim();
});

// 3. Fetch: market data + news always go to the network (never serve stale
//    prices from cache); app shell is network-first with a cache fallback so
//    offline users still see the last successful load, same pattern as the
//    weather app this was forked from.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // FX report JSON/HTML is generated by a scheduled sync and can change daily — never
  // serve a stale cached copy, same reasoning as /api/ below.
  if (
    url.pathname.startsWith('/api/') ||
    url.pathname.startsWith('/data/fx-reports/')
  ) {
    event.respondWith(fetch(event.request));
    return;
  }

  event.respondWith(
    fetch(event.request)
      .then((networkResponse) => {
        const responseClone = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, responseClone));
        return networkResponse;
      })
      .catch(() => caches.match(event.request))
  );
});
