const CACHE_NAME = 'scere-markets-v11';
const ASSETS_TO_CACHE = [
  './',
  './index.html',
  './app.js',
  './nav.js',
  './instruments.js',
  './market-advisories.js',
  './research.html',
  './research.js',
  './fx-intelligence.html',
  './fx-intelligence.js',
  './learn.html',
  './lesson.html',
  './learn.js',
  './learn-content.js',
  './foundation-content.js',
  './forex-content.js',
  './crypto-content.js',
  './crypto-labs.js',
  './due-diligence.html',
  './due-diligence.js',
  './due-diligence-content.js',
  './legend.js',
  './legend-content.js',
  './fund-facts.js',
  './manifesto.html',
  './styles.css',
  './manifest.json',
  'https://cdn.tailwindcss.com'
];

// 1. Install: cache the app shell.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS_TO_CACHE))
  );
  self.skipWaiting();
});

// 2. Activate: drop old cache versions.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.map((key) => (key !== CACHE_NAME ? caches.delete(key) : undefined)))
    )
  );
  self.clients.claim();
});

// 3. Fetch: market data + news always go to the network (never serve stale
//    prices from cache); app shell is network-first with a cache fallback so
//    offline users still see the last successful load, same pattern as the
//    weather app this was forked from.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // FX report JSON/HTML is generated by a scheduled sync and can change daily — never
  // serve a stale cached copy, same reasoning as /api/ below.
  if (
    url.pathname.startsWith('/api/') ||
    url.pathname.startsWith('/data/fx-reports/')
  ) {
    event.respondWith(fetch(event.request));
    return;
  }

  event.respondWith(
    fetch(event.request)
      .then((networkResponse) => {
        const responseClone = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, responseClone));
        return networkResponse;
      })
      .catch(() => caches.match(event.request))
  );
});
