// v19 collapses the home page's mission essay into a <details> disclosure. index.html
// and styles.css both changed, and both are precached — without the bump an existing
// install keeps serving the old thousand-word scroll.
//
// v18 adopts the brand mark and renames the product to Scere Training. Every page's
// <title> and the manifest changed, and there are new icons/ assets an install still
// serving v17 would neither have nor fetch — it would keep showing the old name and the
// hotlinked third-party PWA icon that the manifest no longer points at.
//
// v17 adds progress.js and track.html, and splits the syllabus into a hub plus a page
// per track. An install still serving v16 would keep the old flat 58-row course page
// and would not have progress.js cached at all.
//
// v16 adds ui.js (accessible dialogs, live regions, skeletons, offline banner) and
// changes every page's markup to add landmarks and skip links. An install still
// serving v15 would keep the old pages, which reference a ui.js it has not cached —
// the bump is what keeps the two in step.
//
// v15 ships the two purchase flows. learn.js, research.js and styles.css all changed
// to render buy buttons and per-product access states; without the bump, an existing
// install would keep the cached copies and show a course that cannot be bought.
//
// v14 drops the course bundles: lesson content now lives server-side and is fetched
// per lesson from /api/course, which enforces entitlement. Precaching the old public
// bundles would have kept serving the entire paid course from cache to anyone who
// had visited before the change — the version bump is what actually evicts them.
//
// v13 narrowed the app to three surfaces: the intro page, the course, and the ideas
// desk. Due Diligence, FX Intelligence and the standalone manifesto are retired —
// their routes redirect home (see vercel.json) and precaching them would keep
// serving dead pages to anyone who had already visited. The version bump is what
// evicts them from existing installs.
const CACHE_NAME = 'scere-training-v21';
const ASSETS_TO_CACHE = [
  './',
  './index.html',
  './manifest.json',
  './icons/mark.svg',
  './icons/favicon.svg',
  './icons/favicon-32.png',
  './icons/apple-touch-icon.png',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable-512.png',
  './ui.js',
  './nav.js',
  './i18n.js',
  // The locale files, so a language someone has chosen survives going offline. Only
  // the ones that exist: addAll rejects as a unit, and a 404 on a locale we have not
  // written yet would take the whole app shell down with it.
  './i18n/en.json',
  './i18n/fr.json',
  './i18n/sw.json',
  './research.html',
  './research.js',
  './learn.html',
  './lesson.html',
  './track.html',
  './progress.js',
  './learn.js',
  './country-indicator-copy.js',
  './crypto-labs.js',
  './instruments.js',
  './fund-facts.js',
  './styles.css',
  './manifest.json',
  'https://cdn.tailwindcss.com'
];

// 1. Install: cache the app shell.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS_TO_CACHE))
  );
  self.skipWaiting();
});

// 2. Activate: drop old cache versions.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.map((key) => (key !== CACHE_NAME ? caches.delete(key) : undefined)))
    )
  );
  self.clients.claim();
});

// 3. Fetch: market data + news always go to the network (never serve stale
//    prices from cache); app shell is network-first with a cache fallback so
//    offline users still see the last successful load, same pattern as the
//    weather app this was forked from.
self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);

  // FX report JSON/HTML is generated by a scheduled sync and can change daily — never
  // serve a stale cached copy, same reasoning as /api/ below.
  if (
    url.pathname.startsWith('/api/') ||
    url.pathname.startsWith('/data/fx-reports/')
  ) {
    event.respondWith(fetch(event.request));
    return;
  }

  event.respondWith(
    fetch(event.request)
      .then((networkResponse) => {
        const responseClone = networkResponse.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put(event.request, responseClone));
        return networkResponse;
      })
      .catch(() => caches.match(event.request))
  );
});
