'use strict';

const crypto = require('node:crypto');

const game = require('../../africa-numbers/game.js');
const draws = require('../src/draws.js');
const { CONFIG } = require('../src/config.js');

/**
 * Every figure in the math sheet, computed rather than asserted.
 *
 * The board has 1,000 outcomes, so nothing here needs sampling: win counts are
 * obtained by asking the settlement code itself about every selection against
 * every outcome, one million questions per bet type. A table copied out of a
 * design document and a table derived from the code that pays people are two
 * different documents, and only the second one is worth submitting.
 *
 * The one thing enumeration cannot answer is whether the draw mechanism
 * actually reaches all 1,000 outcomes evenly. That gets a sample, and a
 * deliberately narrow claim about what the sample shows.
 */

const OUTCOMES = 1000;
const TYPE_ORDER = ['straight', 'box6', 'box3', 'front', 'oneDigit', 'twoDigits'];
const WEEK = 7;

/** Every three-digit result, '000' to '999'. */
const ALL_RESULTS = Array.from({ length: OUTCOMES }, (_, n) => String(n).padStart(3, '0'));

/**
 * Every selection the product would accept for a bet type.
 *
 * Generated by asking `validateBet`, not by reasoning about what it ought to
 * accept - so a rule that changes shows up here as a different selection count
 * rather than as a table that quietly stops matching the game.
 */
function selectionsFor(type) {
  const width = game.BET_TYPES[type].digits;
  const total = 10 ** width;
  const out = [];
  for (let n = 0; n < total; n++) {
    const digits = String(n).padStart(width, '0');
    if (game.validateBet({ type, digits, stakeCents: 100, balanceCents: 100 }).ok) out.push(digits);
  }
  return out;
}

/**
 * How many of the 1,000 outcomes each selection wins on.
 *
 * The design claims the count is a property of the bet type alone - that every
 * 6-Way Box wins on exactly six draws, whichever three digits were chosen. That
 * is checkable rather than assertable, so every selection is counted and the
 * spread reported. A type where the count is not uniform is mispriced for some
 * of its selections, which is the quiet way a board becomes unfair.
 */
function winCountsFor(type) {
  const counts = selectionsFor(type).map((digits) => {
    let wins = 0;
    for (const result of ALL_RESULTS) if (game.isHit({ type, digits }, result)) wins++;
    return { digits, wins };
  });

  const values = counts.map((entry) => entry.wins);
  return {
    selections: counts.length,
    min: Math.min(...values),
    max: Math.max(...values),
    uniform: Math.min(...values) === Math.max(...values),
    wins: values[0],
    counts
  };
}

/**
 * What integer rounding does to the return.
 *
 * Two multipliers are fractional, so a payout is rounded to the cent - upward
 * on a half, towards the player. At a whole unit of currency the arithmetic is
 * exact for every multiplier on the board; below that it is not, and the
 * direction and size of the error belong in the sheet rather than in a
 * footnote.
 */
function roundingFor(type, wins, maxStake) {
  const theoretical = (wins / OUTCOMES) * game.BET_TYPES[type].multiplier;
  let worst = { stakeCents: null, rtp: theoretical, deviation: 0 };
  let exactAtWholeUnits = true;

  const minor = 10 ** CONFIG.currency.minorUnits;
  for (let stakeCents = 1; stakeCents <= maxStake; stakeCents++) {
    const gross = game.grossPayoutCents(type, stakeCents);
    const rtp = (wins / OUTCOMES) * (gross / stakeCents);
    const deviation = rtp - theoretical;
    if (Math.abs(deviation) > Math.abs(worst.deviation)) worst = { stakeCents, rtp, deviation };
    if (stakeCents % minor === 0 && gross !== stakeCents * game.BET_TYPES[type].multiplier) {
      exactAtWholeUnits = false;
    }
  }
  return { theoretical, worst, exactAtWholeUnits, maxStake };
}

/** The whole board, derived. */
function board({ maxStake = 10_000 } = {}) {
  return TYPE_ORDER.map((type) => {
    const spec = game.BET_TYPES[type];
    const counted = winCountsFor(type);
    const probability = counted.wins / OUTCOMES;
    const rtp = probability * spec.multiplier;

    return {
      type,
      label: spec.label,
      hint: spec.hint,
      digits: spec.digits,
      multiplier: spec.multiplier,
      selections: counted.selections,
      wins: counted.wins,
      uniform: counted.uniform,
      spread: [counted.min, counted.max],
      probability,
      oneIn: OUTCOMES / counted.wins,
      rtp,
      holdPct: (1 - rtp) * 100,
      // Per unit staked: the return is the multiplier with probability p and
      // nothing otherwise, so the standard deviation is M*sqrt(p(1-p)).
      sd: spec.multiplier * Math.sqrt(probability * (1 - probability)),
      weekly: 1 - ((1 - probability) ** WEEK),
      rounding: roundingFor(type, counted.wins, maxStake)
    };
  });
}

/**
 * Blended hold for an assumed mix of stakes.
 *
 * Illustrative and labelled as such: nobody has taken a bet yet, so any mix is
 * an assumption. The arithmetic is the point - a board is not one hold, it is
 * whatever hold the players choose by what they play.
 */
function mixes(rows) {
  const rate = Object.fromEntries(rows.map((row) => [row.type, row.rtp]));
  const blend = (weights) => {
    const total = Object.values(weights).reduce((sum, weight) => sum + weight, 0);
    const rtp = Object.entries(weights)
      .reduce((sum, [type, weight]) => sum + (weight / total) * rate[type], 0);
    return { weights, rtp, holdPct: (1 - rtp) * 100 };
  };

  return [
    {
      name: 'Traditional board only',
      note: 'What the game would return with no position-free bets on the screen.',
      ...blend({ straight: 50, box6: 20, box3: 10, front: 20 })
    },
    {
      name: 'Even split across the six',
      note: 'The neutral assumption, and the least likely to happen.',
      ...blend({ straight: 1, box6: 1, box3: 1, front: 1, oneDigit: 1, twoDigits: 1 })
    },
    {
      name: 'Frequency-led',
      note: 'What §07 of the architecture is trying to produce: most stakes on the bets that pay often.',
      ...blend({ straight: 20, box6: 10, box3: 5, front: 10, oneDigit: 40, twoDigits: 15 })
    }
  ];
}

// ------------------------------------------------------------- the draw itself

/** Numerical Recipes' Chebyshev erfc. Accurate to about 1.2e-7, which is ample. */
function erfc(x) {
  const z = Math.abs(x);
  const t = 2 / (2 + z);
  const ty = 4 * t - 2;
  const coefficients = [
    -1.3026537197817094, 6.4196979235649026e-1, 1.9476473204185836e-2,
    -9.561514786808631e-3, -9.46595344482036e-4, 3.66839497852761e-4,
    4.2523324806907e-5, -2.0278578112534e-5, -1.624290004647e-6,
    1.303655835580e-6, 1.5626441722e-8, -8.5238095915e-8,
    6.529054439e-9, 5.059343495e-9, -9.91364156e-10,
    -2.27365122e-10, 9.6467911e-11, 2.394038e-12,
    -6.886027e-12, 8.94487e-13, 3.13092e-13,
    -1.12708e-13, 3.81e-16, 7.106e-15
  ];
  let d = 0;
  let dd = 0;
  for (let j = coefficients.length - 1; j > 0; j--) {
    const tmp = d;
    d = ty * d - dd + coefficients[j];
    dd = tmp;
  }
  const answer = t * Math.exp(-z * z + 0.5 * (coefficients[0] + ty * d) - dd);
  return x >= 0 ? answer : 2 - answer;
}

/**
 * Does the draw derivation reach all 1,000 outcomes evenly?
 *
 * Seeds are derived deterministically - sha256 of a counter - so this section
 * reproduces exactly and a reviewer can re-run it and get the same numbers. The
 * claim is correspondingly narrow, and stating it narrowly is the point:
 *
 *   This tests the MAPPING from a seed to a result: the HMAC, the rejection
 *   sampling, and the scaling to 000-999. It says nothing about the entropy of
 *   a real seed, which comes from the platform CSPRNG and is not this test's
 *   business.
 *
 * Chi-square against a uniform expectation over 1,000 buckets, with the tail
 * probability from the Wilson-Hilferty transform, which is the standard normal
 * approximation for a chi-square with many degrees of freedom.
 */
function uniformity({ samples = 1_000_000, drawKey = 'uniformity' } = {}) {
  const buckets = new Uint32Array(OUTCOMES);
  for (let i = 0; i < samples; i++) {
    const seed = crypto.createHash('sha256').update(`math-sheet|${i}`, 'utf8').digest('hex');
    buckets[Number(draws.resultFromSeed(drawKey, seed))] += 1;
  }

  const expected = samples / OUTCOMES;
  let chiSquare = 0;
  for (const observed of buckets) chiSquare += ((observed - expected) ** 2) / expected;

  const df = OUTCOMES - 1;
  const ratio = (chiSquare / df) ** (1 / 3);
  const mean = 1 - 2 / (9 * df);
  const sd = Math.sqrt(2 / (9 * df));
  const z = (ratio - mean) / sd;
  // Two-sided: a fit that is too good is as suspicious as one that is too bad.
  const p = erfc(Math.abs(z) / Math.SQRT2);

  return {
    samples, drawKey, df, chiSquare, z, p,
    expectedPerOutcome: expected,
    minBucket: Math.min(...buckets),
    maxBucket: Math.max(...buckets),
    emptyBuckets: [...buckets].filter((count) => count === 0).length
  };
}

function compute({ samples = 1_000_000, maxStake = 10_000 } = {}) {
  const rows = board({ maxStake });
  return {
    currency: CONFIG.currency,
    outcomes: OUTCOMES,
    runnerCutPct: game.RUNNER_CUT_PCT,
    week: WEEK,
    rows,
    mixes: mixes(rows),
    uniformity: uniformity({ samples }),
    maxStake
  };
}

module.exports = {
  compute, board, mixes, uniformity, winCountsFor, selectionsFor, roundingFor, erfc,
  OUTCOMES, TYPE_ORDER, ALL_RESULTS, WEEK
};
