'use strict';

const { group: thousands, escape, htmlTable, page } = require('./render-helpers.js');
const { CATALOGUE, CALL_LOG, JOURNAL } = require('./events.js');

/**
 * The significant events catalogue, in two renderings from one reconciliation.
 *
 * The list is the easy part. What makes the page worth submitting is that it is
 * checked against the code from two directions on every build, and that the
 * section at the end says what is *not* recorded - which is the section a
 * laboratory reads first and the one a catalogue written by hand never has.
 */

const GROUPS = [
  ['Money', 'Value moving between the operator, a runner and a player.'],
  ['Draws', 'Committing, taking bets, revealing, settling.'],
  ['Promotions', 'What a campaign costs and what it promised.'],
  ['Player protection', 'Limits, exclusions, and who set them.'],
  ['Runner control', 'Who may sell, and from when.'],
  ['Credentials', 'Tokens and PINs. Never their values.'],
  ['Mobile money', 'The only boundary where this system does not control both sides.']
];

/**
 * What a laboratory may expect and will not find. Written by hand, because a
 * generator cannot enumerate an absence - and reviewed every time this document
 * is regenerated, because an out-of-date gap list is worse than none.
 */
const GAPS = [
  {
    title: 'Most events record what happened, not who did it',
    detail: 'Only the two policy events carry the staff member who posted them, taken from their credentials. For everything else - suspending a runner, resetting a PIN, revealing a draw - the actor is in the call log and joined to the event by time and by token digest. A single field on every event would be better, and is the first thing to add.'
  },
  {
    title: 'The journal is append-only by storage, not by cryptography',
    detail: 'Nothing is ever updated in place, balances are derived rather than stored, and a verification pass proves the cache matches the entries. But a writer with database access could still edit history, and nothing in the record would show it. A hash chain over the journal - each entry carrying the digest of the one before - would make that detectable. It is not built.'
  },
  {
    title: 'The call log is a file, and the events are not',
    detail: 'Ledger events are as durable as the money. The call log - which is the only record of a read - is an append-only JSONL file with no rotation, no retention period and no shipping. "Who looked at this player\'s wallet" is answered by something that can be lost in a way "who moved money" cannot.'
  },
  {
    title: 'A direct caller leaves no call-log line',
    detail: 'Anything driving the operator object directly - a script, a migration, a console session on the host - writes its ledger events but no call-log line, so the actor is unrecorded. Restricting production to the service, and saying so in the access policy, is the answer rather than more logging.'
  },
  {
    title: 'No retention policy is written down',
    detail: 'The ledger keeps everything permanently by construction. Nothing states how long the call log is kept, where it is shipped, or who may read it. That is a policy document, and it does not exist yet.'
  },
  {
    title: 'Nothing is recorded about the software itself',
    detail: 'A failed build verification, a restore from backup, a change to a rate limit or a body cap: none of these produces an event. The build id is stamped on every call-log line, which is where a deployment becomes visible, and that is the whole of it.'
  },
  {
    title: 'No thresholds, no alerts',
    detail: 'A large win, an unusual velocity, a runner reconciling badly for a third day: all of these are derivable from the journal and none of them raises anything. The reports are pull, not push.'
  },
  {
    title: 'The mobile money simulator ships in the certified build',
    detail: 'There is no driver for a real provider yet, so the composition root has nothing else to wire and the simulator is in the runtime tree. Once a real driver exists, a simulator that can stand in for it should be absent from a certified build in the same way and for the same reason that forced draw outcomes are.'
  }
];

const RECORDS = {
  journal: ['Journal', 'A double-entered transaction. Money moved.'],
  events: ['Event', 'A fact with no money in it. Same store, same durability.']
};

// ------------------------------------------------------------------ markdown

function markdown(data) {
  const { counts, unexercised } = data;
  const out = [];
  const push = (...lines) => out.push(...lines);

  push('# Africa Numbers — significant events');
  push('');
  push('Every event this system records: what it means, which record it lands in, and');
  push('what it carries. Generated by `npm run events` and checked against the code from');
  push('two directions on every build.');
  push('');
  push('```');
  push(`catalogued        ${counts.catalogued}`);
  push(`found in the code ${counts.inCode}`);
  push(`observed written  ${counts.exercised}`);
  push(`transactions      ${counts.journal}   double-entered, money moved`);
  push(`events            ${counts.events}   a fact with no money in it`);
  push('```');
  push('');
  push('**A kind in the code and not on this page fails the build.** So does a kind on');
  push('this page and not in the code, and so does one filed under the wrong record. The');
  push('check runs the system, watches what it writes, and compares.');
  push('');
  if (unexercised.length) {
    push(`Documented but not reached by any scenario: ${unexercised.join(', ')}. "We record`);
    push('this" and "we have seen this recorded" are different claims and the page does not');
    push('blur them.');
  } else {
    push('Every kind on this page was observed being written while the system was exercised.');
  }
  push('');

  push('## Where an event lives');
  push('');
  push('| | |');
  push('| --- | --- |');
  push('| **Journal** | A double-entered transaction. Append-only, durable, and the balances are derived from it rather than stored beside it. |');
  push('| **Event** | A fact with no money in it — a suspension, a policy change, a PIN lockout. Same store, same durability, same append-only guarantee. |');
  push('| **Call log** | One line per HTTP call, to an append-only file. The only record of a *read*. |');
  push('');

  for (const [name, blurb] of GROUPS) {
    const entries = CATALOGUE.filter((entry) => entry.group === name);
    push(`## ${name}`);
    push('');
    push(blurb);
    push('');
    for (const entry of entries) {
      push(`### \`${entry.kind}\``);
      push('');
      push(`**${entry.title}** — ${RECORDS[entry.record][0].toLowerCase()}, about a ${entry.subject}.`);
      push('');
      push(entry.what);
      push('');
    }
  }

  push('## The call log');
  push('');
  push('One line per HTTP call — reads as well as writes, because "who looked at this');
  push('player\'s wallet" carries the same weight as "who moved money".');
  push('');
  push('| Field | |');
  push('| --- | --- |');
  for (const [field, meaning] of CALL_LOG.fields) push(`| \`${field}\` | ${meaning} |`);
  push('');
  push(`**Never recorded:** ${CALL_LOG.never.join(', ')}.`);
  push('');

  push('## What is not recorded');
  push('');
  push('The section a catalogue written by hand never has.');
  push('');
  for (const gap of GAPS) {
    push(`### ${gap.title}`);
    push('');
    push(gap.detail);
    push('');
  }

  push('_Generated by `npm run events` from the source and from a full exercise of the');
  push('system. Do not edit the catalogue by hand._');
  push('');

  return out.join('\n');
}

// ---------------------------------------------------------------------- html

function html(data) {
  const { counts, unexercised } = data;

  const groups = GROUPS.map(([name, blurb]) => {
    const rows = CATALOGUE.filter((entry) => entry.group === name).map((entry) => ({
      key: entry.kind,
      cells: [
        `<code>${escape(entry.kind)}</code>`,
        `<strong>${escape(entry.title)}</strong><p class="what">${escape(entry.what)}</p>`,
        entry.record === JOURNAL ? 'Journal' : 'Event',
        escape(entry.subject)
      ]
    }));
    return `<section>
    <h2>${escape(name)}</h2>
    <p>${escape(blurb)}</p>
    ${htmlTable({
      columns: [{ label: 'Kind' }, { label: 'What it means' }, { label: 'Record' }, { label: 'About' }],
      rows
    })}
  </section>`;
  }).join('\n\n  ');

  const callLog = htmlTable({
    columns: [{ label: 'Field' }, { label: 'What it holds' }],
    rows: CALL_LOG.fields.map(([field, meaning]) => ({
      key: field, cells: [`<code>${escape(field)}</code>`, escape(meaning)]
    }))
  });

  const gaps = GAPS.map((gap) => `<div class="derivation">
          <h3>${escape(gap.title)}</h3>
          <p>${escape(gap.detail)}</p>
        </div>`).join('\n        ');

  return page({
    title: 'Africa Numbers Significant Events',
    stamp: ['Significant events', 'Africa Numbers', 'Checked from both directions'],
    heading: 'What the system writes down',
    standfirst: `Every event this system records, what it means, and which record it lands in.
      A kind in the code and not on this page fails the build; so does a kind on this page
      and not in the code, and so does one filed under the wrong record.`,
    body: `
  <section>
    <span class="verdict">${unexercised.length === 0 ? 'All observed being written' : `${unexercised.length} not exercised`}</span>
    <h2>The count</h2>
<pre>catalogued         ${counts.catalogued}
found in the code  ${counts.inCode}
observed written   ${counts.exercised}
transactions       ${counts.journal}   double-entered, money moved
events             ${counts.events}   a fact with no money in it</pre>
    <p>The check is not a spell-check. It scans the source for every kind the code can
      write, then runs the system and watches what it does write and where it lands, and
      compares both against this page.</p>
    ${unexercised.length === 0
      ? '<p>Every kind here was observed being written while the system was exercised.</p>'
      : `<p>Documented but not reached by any scenario: ${escape(unexercised.join(', '))}. &ldquo;We record
        this&rdquo; and &ldquo;we have seen this recorded&rdquo; are different claims.</p>`}
    ${htmlTable({
      columns: [{ label: 'Record' }, { label: 'What it is' }],
      rows: [
        { key: 'journal', cells: ['Journal', 'A double-entered transaction. Append-only, durable, and balances are derived from it rather than stored beside it.'] },
        { key: 'events', cells: ['Event', 'A fact with no money in it &mdash; a suspension, a policy change, a PIN lockout. Same store, same durability.'] },
        { key: 'call', cells: ['Call log', 'One line per HTTP call, to an append-only file. The only record of a <em>read</em>.'] }
      ]
    })}
  </section>

  ${groups}

  <section>
    <h2>The call log</h2>
    <p>One line per HTTP call &mdash; reads as well as writes, because &ldquo;who looked at this
      player's wallet&rdquo; carries the same weight as &ldquo;who moved money&rdquo;.</p>
    ${callLog}
    <div class="callout">
      <p><strong>Never recorded:</strong> ${escape(CALL_LOG.never.join(', '))}.</p>
    </div>
  </section>

  <section>
    <h2>What is not recorded</h2>
    <p>The section a catalogue written by hand never has.</p>
    <div class="derivations">
        ${gaps}
    </div>
  </section>

  <p class="footer">Generated by <code>npm run events</code> from the source and from a full
    exercise of the system. The catalogue is not edited by hand, and continuous integration
    fails if the code and this page disagree.</p>
`
  });
}

module.exports = { markdown, html, GROUPS, GAPS };
